Course info (getting by course id)
Barrosg99/codify-back pull request #8
Opened 2021-02-04 22:37 UTC by luucaskenji

2021-02-04 22:46 UTC, oliverdettenborn approved these changes

2021-02-04 23:19 UTC, oliverdettenborn approved these changes

2021-02-05 18:53 UTC, vagnerpavani requested changes

2021-02-05 18:53 UTC, vagnerpavani commented on tests/controllers/coursesController.test.js
>  describe('POST /course', () => {
Esse teste seria unitário, porem seu describe esta se referindo a rota. Em testes unitários nossos describes podem se referir a função e cada it seria um teste nessa função.

2021-02-05 19:03 UTC, oliverdettenborn approved these changes

2021-02-05 19:38 UTC, merged